### ISSUE TITLE
Still Being Developed

### ISSUE THREAD

**Issue by joshua1** [azukiapp/ecto-rethinkdb#1]
Hi @nuxlli Am interested in what you have done here. does it still work. I have been looking for an ecto Adpater (especially for rethink and couchbase). I would appreciate it if there are pointers especially for the query builder

**Comment by nuxlli** [comment]
Hi @joshua1,

Unfortunately the work on this adapter wasn't even finished. I've been involved the last years with the project http://azk.io and I couldn't move on in this project nor in its related: https://github.com/azukiapp/elixir-rethinkdb
